---
- name: 'Task 3: File Content'
  hosts: all
  become: yes
  tasks:
    - name: Modify /etc/motd for hosts in proxy_host group
      lineinfile:
        path: /etc/motd
        line: Welcome to HAProxy server
      when: inventory_hostname in groups['proxy_host']

    - name: Modify /etc/motd for hosts in webservers group
      lineinfile:
        path: /etc/motd
        line: Welcome to Apache server
      when: inventory_hostname in groups['webservers']

    - name: Modify /etc/motd for hosts in database group
      lineinfile:
        path: /etc/motd
        line: Welcome to MySQL server
      when: inventory_hostname in groups['database']