---
- name: Software repositories
  hosts: database
  become: yes
  user: root
  tasks:
    - name: Create YUM repository file
      yum_repository:
        name: mysql56-community
        description: MySQL 5.6 YUM Repo
        baseurl: http://repo.example.com/rpms
        enabled: yes