---
- name: "Task 18. Create and Use Templates to Create Customised Configuration File"
  hosts: all
  become: yes
  tasks:

    - name: Create server_list.txt on every host from database group
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        owner: automation
        mode: '0600'
        setype: net_conf_t
        force: yes
      when: inventory_hostname in groups['database']