---
- name: 'Task 13: Use Conditionals to Control Play Execution'
  hosts: all
  become: yes
  tasks:
  
    - name: Configure server with more than 2GB of RAM
      ansible.posix.sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when:
        - ansible_memtotal_mb > 2048
    
    - name: Configure server with less than 2GB of RAM
      debug:
        msg: "Server memory less than 2048MB"
      when:
        - ansible_memtotal_mb < 2048
